# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS build
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install && npm run build && npm prune --production

FROM node:lts-alpine
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/build ./build
COPY --from=build /app/package.json ./package.json

# Default environment, can be overridden
ENV PLANE_API_HOST_URL=https://api.plane.so/

# Start the MCP server
ENTRYPOINT ["node", "build/index.js"]
